name: Generate and deploy graphs

on: push

jobs:
  run-benchmark-monitor:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: cz4rs/benchmark_monitor
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: benchmark-results

    - name: Process available benchmark results
      run: |-
        python3 -m venv env
        source env/bin/activate
        pip install wheel
        pip install -r requirements.txt
        python benchmark_monitor.py -d ./benchmark-results -o output

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: output
        repository-name: cz4rs/cz4rs.github.io
        branch: master
        token: ${{ secrets.API_TOKEN_GITHUB }}
